
/*
Auto-generated by CVXPYgen on July 17, 2025 at 15:09:13.
Content: Variable definitions.
*/

#include "cpg_workspace.h"

// Vector containing flattened user-defined parameters
cpg_float cpg_params_vec[7] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)2.24089319920145779719,
(cpg_float)1.86755799014996748397,
(cpg_float)-0.97727787987641101530,
(cpg_float)1.00000000000000000000,
};

// Sparse mappings from user-defined to canonical parameters
cpg_int canon_G_map_i[7] = {
6,
6,
6,
0,
6,
1,
2,
};
cpg_int canon_G_map_p[8] = {
0,
1,
2,
3,
4,
5,
6,
7,
};
cpg_float canon_G_map_x[7] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-2.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-2.00000000000000000000,
(cpg_float)-2.00000000000000000000,
};
cpg_csc canon_G_map = {canon_G_map_p, canon_G_map_i, canon_G_map_x, 7};

cpg_int canon_h_map_i[5] = {
6,
6,
3,
4,
5,
};
cpg_int canon_h_map_p[8] = {
0,
0,
0,
1,
2,
3,
4,
5,
};
cpg_float canon_h_map_x[5] = {
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-2.00000000000000000000,
(cpg_float)-2.00000000000000000000,
(cpg_float)-2.00000000000000000000,
};
cpg_csc canon_h_map = {canon_h_map_p, canon_h_map_i, canon_h_map_x, 5};

// Canonical parameters
cpg_float canon_c[3] = {
(cpg_float)1.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_float canon_c_conditioning[3] = {
(cpg_float)1.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_int canon_G_i[7] = {
2,
3,
0,
4,
1,
4,
5,
};
cpg_int canon_G_p[4] = {
0,
2,
4,
7,
};
cpg_float canon_G_x[7] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};
cpg_csc canon_G = {canon_G_p, canon_G_i, canon_G_x, 7};

cpg_int canon_G_conditioning_i[7] = {
2,
3,
0,
4,
1,
4,
5,
};
cpg_int canon_G_conditioning_p[4] = {
0,
2,
4,
7,
};
cpg_float canon_G_conditioning_x[7] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};
cpg_csc canon_G_conditioning = {canon_G_conditioning_p, canon_G_conditioning_i, canon_G_conditioning_x, 7};

cpg_float canon_h[7] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-4.48178639840291559437,
(cpg_float)-3.73511598029993496795,
(cpg_float)1.95455575975282203061,
};

cpg_float canon_h_conditioning[7] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-4.48178639840291559437,
(cpg_float)-3.73511598029993496795,
(cpg_float)1.95455575975282203061,
};

// Struct containing canonical parameters
Canon_Params_t Canon_Params = {
.c = (cpg_float *) &canon_c,
.d = 0.00000000000000000000,
.A = 0,
.b = 0,
.G = &canon_G,
.h = (cpg_float *) &canon_h,
};

Canon_Params_t Canon_Params_conditioning = {
.c = (cpg_float *) &canon_c_conditioning,
.d = 0.00000000000000000000,
.A = 0,
.b = 0,
.G = &canon_G_conditioning,
.h = (cpg_float *) &canon_h_conditioning,
};

// Struct containing flags for outdated canonical parameters
Canon_Outdated_t Canon_Outdated = {
.c = 1,
.d = 1,
.A = 1,
.b = 1,
.G = 1,
.h = 1,
};

// User-defined variables
cpg_float x[2] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

// Struct containing primal solution
CPG_Prim_t CPG_Prim = {
.x = (cpg_float *) &x,
};

// Dual variables associated with user-defined constraints
cpg_float d0[2] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

// Struct containing dual solution
CPG_Dual_t CPG_Dual = {
.d0 = (cpg_float *) &d0,
};

// Struct containing solver info
CPG_Info_t CPG_Info = {
.obj_val = 0,
.iter = 0,
.status = 0,
.pri_res = 0,
.dua_res = 0,
};

// Struct containing solution and info
CPG_Result_t CPG_Result = {
.prim = &CPG_Prim,
.dual = &CPG_Dual,
.info = &CPG_Info,
};

// Struct containing solver settings
Canon_Settings_t Canon_Settings = {
.feastol = 1e-8,
.abstol = 1e-8,
.reltol = 1e-8,
.feastol_inacc = 1e-4,
.abstol_inacc = 5e-5,
.reltol_inacc = 5e-5,
.maxit = 100,
};

// ECOS array of SOC dimensions
cpg_int ecos_q[1] = {
5,
};

// ECOS workspace
pwork* ecos_workspace = 0;

// ECOS exit flag
cpg_int ecos_flag = -99;
