# This workflow will install Python dependencies and run pytest tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_E2E_macOS:

    runs-on: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Test with pytest
      run: |
        $CONDA/bin/pytest tests/
