# This workflow will install Python dependencies and run pytest tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: [ ubuntu-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        conda update -n base conda
        conda install -c conda-forge cvxpy
        conda install -c anaconda cmake
        conda install pybind11
    - name: Test with pytest
      run: |
        cd tests
        pytest
